services:
  python-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/msql

volumes:
  mysql-data:
